name: Publish Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm test

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Publish to NPM
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: ad-m/github-push-action@v0.5.0
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm version minor
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Commit files
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git commit -m 'Add changes' -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: release
          github_token: ${{secrets.GITHUB_TOKEN}}
